networks:
  apps-proxy:
    external: true
    name: apps-proxy

services:
  catcher:
    image: scatcher
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./storage:/app/storage
    networks:
      - "apps-proxy"
    labels:
      traefik.enable: true
      traefik.docker.network: apps-proxy
      traefik.http.routers.catcher.entrypoints: websecure
      traefik.http.routers.catcher.rule: Host(`catcher.rs.shadoll.dev`)
      traefik.http.routers.catcher.tls: true
      traefik.http.routers.catcher.tls.certresolver: letsencrypt
      traefik.http.services.catcher.loadbalancer.server.port: 5000

