/*
Show quick usage manual
*/
GET https://catcher.rs.shadoll.dev/api/__help
/*
Show last request
*/
###
GET https://catcher.rs.shadoll.dev/api/__last_request
/*
Show all history
*/
###
GET https://catcher.rs.shadoll.dev/api/__history
/*
Show one history record by number
*/
###
GET https://catcher.rs.shadoll.dev/api/__history/1
/*
Clear all history records
*/
###
GET https://catcher.rs.shadoll.dev/api/__clear
/*
Requests catcher
*/
###
POST https://catcher.rs.shadoll.dev
Content-Type: application/json

{
    "message": "Hello, World!",
    "level": "info",
    "tags": [
        "example",
        "hello-world"
    ],
    "extra": {
        "key": "value",
    }
}
###
GET https://catcher.rs.shadoll.dev?message=Hello%2C%20World%21&level=info&tags=example&tags=hello-world&extra[key]=value