name: Docker Image CI

on:
  push:
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "compose.yml"
  pull_request:
    paths:
      - "Dockerfile"
      - "requirements.txt"
      - "compose.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/shadoll/scatcher:latest

      - name: Push the Docker image
        run: docker push ghcr.io/shadoll/scatcher:latest
